= Abnahmeprotokoll: {project-name}
include::../_includes/default-attributes.inc.adoc[]

== Projektangaben

// Link und Datum ergänzen

Thema: {project-name}

Zeitraum:

GitHub Repository: https://github.com/mpeeps02/I2_Webuserinterface_Datenbankverwaltung

== Abnahmedokumentation

=== Abnahme

Datum:

Zeit:

Abnahmeumgebung:

=== Lieferumfang

* Software in folgender Form:
* Benutzeranleitung
* Betriebsanleitung
* Anforderungsspezifikationen
* Entwicklerdokumention
* Testdokumentation
* Lizenz

=== Funktionalität

// Use Cases, überarbeitetes Modell noch hinzufügen
//use case Erfüllung updaten
[%header, cols="3,1,3"]

|===
|UseCase/Szenario | Erfüllt | Anmerkung
|Use-Case: Log-Out (UC01) | Ja | |
Use-Case: Filterung nach Land, Hochule und Vertragstyp (UC02)| Ja| |
Use-Case: Verwalten von Ansprechpersonen und Fakultäten (UC03)| Ja | |
Use-Case: Anlegen neuer Verträge (UC04)| Ja | |
Use-Case: Anlegen neuer Universitäten (UC05)| Ja | |
Use-Case: Erzeugen von Berichten (UC06)| Ja | |
Use-Case: Exportieen von Berichten (UC07)| Ja | |
Use-Case: Löschen von Datensätzen (UC08)| Ja | |
Use-Case: exterene Informationsabfrage (UC09)| Nein | |
Use-Case: Möglichkeit zum Bearbeiten und Anlegen von Fakultäten (UC10)| Ja | |
|===



=== Systemweite funktionale Anforderungen

[%header, cols="3,1,3"]

|===
|Anforderung | Erfüllt | Anmerkung |
SWFA-1: Das System muss jegliche Daten bezüglich den Hochschulpartnerschaften speichern. Zur Überprüfung wird die Seite nach dem Speichern neu geladen. | |  | SWFA-2: Zugriff auf das Verwaltungsfrontend dürfen lediglich autorisierte Mitarbeiter/-innen der Stabstelle Internationales haben. Zur Überprüfung wird versucht, das Verwaltungsfrontend außerhalb des HTW-Netzes zu öffnen sowie sich mit falschen Login-Daten anzumelden.| | |
|===

=== Qualitätsanforderungen für das Gesamtsystem

==== Benutzbarkeit (Usability)

[%header, cols="3,1,3"]

|===
|Anforderung | Erfüllt | Anmerkung |
NFAU-1: Das System sollte benutzerfreundlich formatiert und bedienbar sein, für kleine als auch größere PC-Monitore. Zur Überprüfung werden PC-Monitore verschiedensten Größen bedient. | || NFAU-2: Das Verwaltungsfrontend sollte auf verschiedenen Betriebssystemen mit unterschiedlichen Browsern laufen. Zur Überprüfung wird das Verwaltungsfrontend auf Rechner mit den gängigen Betriebssystemen und deren Browsern aufgerufen. |
|===

==== Zuverlässigkeit (Reliability)

[%header, cols="3,1,3"]

|===
|Anforderung | Erfüllt | Anmerkung |
NFAR-1: Beim Abruf eines vorherigen Zustandes der Datenbank, muss das Verwaltungsfrontend weiterhin funktionieren. Zur Überprüfung werden Backups der Datenbank hochgeladen. | | | NFAR-2: Es besteht die Möglichkeit, dass Verwaltungs- und Informationsfrontend gleichzeitig Daten abrufen können.
Zur Überprüfung wird an einem Rechner im Verwaltungsfrontend ein bestehender Datensatz modifiziert, während dieser parallel an einem anderem Rechner im Informationsfrontend angesehen wird.| | |NFAR-3: Das System muss paralleles Lesen und Schreiben im Verwaltungsfrontend unterstützen. (Multi-User-System) Zur Überprüfung werden jeweils zwei verschiedene Login-Sessions laufen, um einerseits einen Datensatz zu lesen und andererseits parallel dazu einen Datensatz zu schreiben. |||
|===

//Damit 2.5.3 Effizienz auf einer neuen Seite, ohne Zwischenbruch erscheint, bei Änderungen "{empty} +" entfernen/hinzufügen
{empty} +
{empty} +
{empty} +
{empty} +
{empty} +
{empty} +
{empty} +

==== Effizienz (Performance)

[%header, cols="3,1,3"]

|===
|Anforderung | Erfüllt | Anmerkung |
NFAP-1: Das Wechseln von Seiten innerhalb des Verwaltungsforntends sollte innerhalb maximal 3 Sekunden stattfinden. Zur Überprüfung werden Seitenaufrufe per Skript simuliert und dabei auf deren Antwortzeit gemessen. |||NFAP-2: Datenbankrelevante Funktionen sollten möglichst schnell, maximal in 2 Sekunden, ausführbar sein. Zur Überprüfung werden Funktionen per SQL-Befehle ausgeführt und dabei auf deren Ausführungszeit gemessen. |
|===

==== Wartbarkeit (Supportability)

[%header, cols="3,1,3"]
|===
|Anforderung | Erfüllt | Anmerkung |
NFAS-1: Übersichtliche und ausführliche Hinweise/Dokumentation, um Erweiterbarkeit zu erleichtern.| | |
NFAS-2: Mögliche Erweiterbarkeit des Systems. Zur Überprüfung wird im Verlauf des Projektes das System stetig um neue Funktionen erweitert.|
|===

=== Übergabe
//SHK und Team ?

Nach der Übergabe des Projektes übernehmen wir keine Gewährleistung. Nach dem 03.07.2023 liegt die Verantwortung für die Nutzung und den Betrieb des Projektes bei dem Auftraggeber.

Der Software-Stand wird am 29.06.2023 durch ... auf den Server übertragen.

Das Github Repository wird an die jetzige Studentischehilfskraft Benjamin Kunat übergeben.


== Unterschriften

Hiermit wird die Abnahme vollständig / mit Mängeln bestätigt.

|===
|> |>
| Unterschrift Themenersteller/in  | Unterschrift Projektleiter/in
|===