= Abnahmeprotokoll: {project-name}

include::../_includes/default-attributes.inc.adoc[]

== Projektangaben

// Link und Datum ergänzen

Thema: {project-name}

Zeitraum:

GitHub Repository: https://github.com/mpeeps02/I2_Webuserinterface_Datenbankverwaltung

== Abnahmedokumentation

=== Abnahme

Datum:

Zeit:

Abnahmeumgebung:

=== Lieferumfang

* Software in folgender Form:
* Benutzeranleitung
* Betriebsanleitung
* Anforderungsspezifikationen
* Entwicklerdokumention
* Testdokumentation

=== Funktionalität

// Use Cases, überarbeitetes Modell noch hinzufügen
//use case Erfüllung updaten
[%header, cols="3,1,3"]

|===
|UseCase/Szenario | Erfüllt | Anmerkung
|Use-Case: Log-Out (UC01) | Ja | |
Use-Case: Filterung nach Land, Hochule und Vertragstyp (UC02)| Ja| |
Use-Case: Verwalten von Ansprechpersonen und Fakultäten (UC03)| Ja | |
Use-Case: Anlegen neuer Verträge (UC04)| Ja | |
Use-Case: Anlegen neuer Universitäten (UC05)| Ja | |
Use-Case: Erzeugen von Berichten (UC06)| Nein | |
Use-Case: Exportieen von Berichten (UC07)| Nein | |
Use-Case: Löschen von Datensätzen (UC08)| Nein | |
Use-Case: exterene Informationsabfrage (UC09)| Nein | |
|===



=== Systemweite Anforderungen

[%header, cols="3,1,3"]

|===
|Anforderung | Erfüllt | Anmerkung
|===

== Unterschriften

Hiermit wird die Abnahme vollständig / mit Mängeln bestätigt.

|===
|> |>
| Unterschrift Themenersteller/in  | Unterschrift Projektleiter/in
|===