= Abnahmeprotokoll: {project-name}
include::../_includes/default-attributes.inc.adoc[]

== Projektangaben

// Link und Datum ergänzen

Thema: {project-name}

GitHub Repository: https://github.com/mpeeps02/I2_Webuserinterface_Datenbankverwaltung

== Abnahmedokumentation

=== Abnahme

Datum: 30.06.2023

Zeit: 11Uhr

=== Lieferumfang

* Software in folgender Form: als Link für die VM
* Anwenderdokumentation
* Betriebsanleitung
* Entwicklerdokumention
* Testdokumentation
* Lizenz: CC-BY-4.0

=== Funktionalität


//use case Erfüllung updaten
[%header, cols="3,1,3"]

|===
|UseCase/Szenario | Erfüllt | Anmerkung
|Use-Case: Log-Out (UC01) | Ja| |
Use-Case: Filterung nach Land, Hochule und Vertragstyp (UC02)| Ja| |
Use-Case: Verwalten von Ansprechpersonen und Fakultäten (UC03)| Ja |In Absprache entfernt |
Use-Case: Anlegen neuer Verträge (UC04)| Ja | |
Use-Case: Anlegen neuer Universitäten (UC05)| Ja | |
Use-Case: Erzeugen von Berichten (UC06)|Ja | Zu erweitern: Filterung nach nur aktiven Verträgen |
Use-Case: Exportieren von Berichten (UC07)| Ja| |
Use-Case: Löschen von Datensätzen (UC08)| Ja | Super User mit Löschrechten und Normaler User ohne Löschrechte implementiert|
Use-Case: exterene Informationsabfrage (UC09)| Ja| |
Use-Case: Möglichkeit zum Bearbeiten und Anlegen von Fakultäten (UC10)|Teilweise | Nur das Anlegen von Fakultäten ist möglich.   |
|===

== Zusätzliche Funktionalitäten

[%header, cols="3,1,3"]

|===
|Funktionalität | Erfüllt | Anmerkung |
Mentor Anlegen| Ja | |
Mentor Bearbeiten | Ja | |
Land Hinzufügen |  | Diese Funktionalität ist im Code vorhanden, wurde aber wegen Speicherprobleme nicht implementiert.|
Land Bearbeiten/Löschen |  | Nicht implementiert
|===

=== Systemweite funktionale Anforderungen

[%header, cols="3,1,3"]

|===
|Anforderung | Erfüllt | Anmerkung |
SWFA-1: Das System muss jegliche Daten bezüglich der Hochschulpartnerschaften speichern. Zur Überprüfung wird die Seite nach dem Speichern neu geladen. | Ja|  | SWFA-2: Zugriff auf das Verwaltungsfrontend dürfen lediglich autorisierte Mitarbeitende der Stabsstelle Internationales haben. Zur Überprüfung wird versucht, das Verwaltungsfrontend außerhalb des HTW-Netzes zu öffnen, sowie sich mit falschen Login-Daten anzumelden.| Ja| |
|===

=== Qualitätsanforderungen für das Gesamtsystem

==== Benutzbarkeit (Usability)

[%header, cols="3,1,3"]

|===
|Anforderung | Erfüllt | Anmerkung |
NFAU-1: Das System sollte benutzerfreundlich formatiert und bedienbar sein, für kleine als auch größere PC-Monitore. Zur Überprüfung werden PC-Monitore verschiedenster Größen bedient. |Ja || NFAU-2: Das Verwaltungsfrontend sollte auf verschiedenen Betriebssystemen mit unterschiedlichen Browsern laufen. Zur Überprüfung wird das Verwaltungsfrontend auf Rechner mit den gängigen Betriebssystemen und deren Browsern aufgerufen. |
|===

==== Zuverlässigkeit (Reliability)

[%header, cols="3,1,3"]

|===
|Anforderung | Erfüllt | Anmerkung |
NFAR-1: Beim Abruf eines vorherigen Zustandes der Datenbank, muss das Verwaltungsfrontend weiterhin funktionieren. Zur Überprüfung werden Backups der Datenbank hochgeladen. |Ja| Es wurde erfolgreich ein neuees Backup eingeführt.| NFAR-2: Es besteht die Möglichkeit, dass Verwaltungs- und Informationsfrontend gleichzeitig Daten abrufen können.
Zur Überprüfung wird an einem Rechner im Verwaltungsfrontend ein bestehender Datensatz modifiziert, während dieser parallel an einem anderem Rechner im Informationsfrontend angesehen wird.| Ja | |NFAR-3: Das System muss paralleles Lesen und Schreiben im Verwaltungsfrontend unterstützen. (Multi-User-System) Zur Überprüfung werden jeweils zwei verschiedene Login-Sessions laufen, um einerseits einen Datensatz zu lesen und andererseits parallel dazu einen Datensatz zu schreiben. |Ja|
|===

//Damit 2.5.3 Effizienz auf einer neuen Seite, ohne Zwischenbruch erscheint, bei Änderungen "{empty} +" entfernen/hinzufügen
{empty} +
{empty} +
{empty} +
{empty} +
{empty} +
{empty} +
{empty} +

==== Effizienz (Performance)

[%header, cols="3,1,3"]

|===
|Anforderung | Erfüllt | Anmerkung |
NFAP-1: Das Wechseln von Seiten innerhalb des Verwaltungsfrontends sollte in maximal 3 Sekunden stattfinden. Zur Überprüfung werden Seitenaufrufe per Skript simuliert und dabei auf deren Antwortzeit gemessen. |Ja||NFAP-2: Datenbankrelevante Funktionen sollten möglichst schnell, maximal in 2 Sekunden, ausführbar sein. Zur Überprüfung werden Funktionen per SQL-Befehle ausgeführt und dabei auf deren Ausführungszeit gemessen. |
|===

==== Wartbarkeit (Supportability)

[%header, cols="3,1,3"]
|===
|Anforderung | Erfüllt | Anmerkung |
NFAS-1: Übersichtliche und ausführliche Hinweise/Dokumentation werden zur Verfügung gestellt, um Erweiterbarkeit zu erleichtern.| Ja | |
NFAS-2: Mögliche Erweiterbarkeit des Systems. Zur Überprüfung wird im Verlauf des Projektes das System stetig um neue Funktionen erweitert.|Ja ||
|===

=== Übergabe

Nach der Übergabe des Projektes übernehmen wir keine Gewährleistung. Nach dem 01.07.2023 liegt die Verantwortung für die Nutzung und den Betrieb des Projektes bei dem Auftraggeber.

Der Software-Stand wird am dem Wochendende nach dem 30.06.2023 durch die Studentische Hilfskraft und die Projektgrppe I2 auf den Server übertragen.

Das Github Repository wird an die jetzige Studentischehilfskraft Benjamin Kunat übergeben.


== Unterschriften

Hiermit wird die Abnahme vollständig / mit Mängeln bestätigt.

|===
|> |>
| Unterschrift Themenerstellerin  | Unterschrift Projektleiterin
|===