= Design: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute

== Allgemeine Informationen
Dieses Dokument enthält Modelle/Beschreibungen zu diskreten Entwurfsentscheidungen, die aus einzelnen Use-Cases und den Konzepten des Architecture-Notebooks hervorgehen.


// tag::include_development[]

== Technische Designaspekte
Technische Designaspekte beschreiben Entwurfsentscheidungen, die direkten Einfluss auf die Funktionsweise einzelner Systemkomponenten haben.

=== Datenbankserver

Es wird ein bereits existenter MariaDB Datenbankserver vom Rechenzentrum genutzt, dieser führt täglich automatische Backups aus. Außerdem obliegt somit auch dem Rechenzentrum die Nutzerverwaltung. Dadurch besitzt der DB-Server eine exzellente Verfügbarkeit, Skalierung und Wartbarkeit.

==== Datenbankmodell

Aufgrund der geforderten Kompatibilität mit dem Informationsfrontend ist die Datenbankstruktur weitestgehend vorgeschrieben und festgelegt. Unsere Vorgruppen haben hierbei bereits eine vielzahl an Änderungen vorgenommen, um die Komplexität und Effizienz zu steigern aber auch die Qualität der Datensätze zu erhöhen.

Darunter beispielsweise die Auflösung einiger 1:n Beziehungen von Hochschulen und ihren Ansprechpartnern .


In folgendem Diagramm wurden Spalten ohne Beziehungen weggelassen, um eine bessere Übersicht zu erzielen. 
//Fix folgt

:imagesdir: images
.physisches Entity-Relationship-Diagram (der Vorgruppe entnommen)
image::physical_erm.svg[physisches Entity-Relationship-Diagram (der Vorgruppe entnommen)]

==== Tabellen

Unten stehend werden alle enthaltenen Tabellen aufgelistet, erläutert sowie deren Möglichkeiten innerhalb des Verwaltungsforntends aufgezeigt:

// tag::explain_tables[]

|===
|Tabelle |Inhalt |Modifikation durch Verwaltungsfrontend

|new_tbl_faculty |Fakultäten der HTW |(Anlegen, Ändern, Deaktivieren)

|new_tbl_mentor |Betreuer der Hochschulverträge (der HTW) |Anlegen, Ändern, Deaktivieren

|new_tbl_gender |Geschlechterauswahl für Mentoren sowie Ansprechpersonen |-

// |new_tbl_country |so gut wie alle Länder der Welt |-

|tbl_institute |Partnerhochschule, International office |auf Informationsfrontend: Anlegen, Ändern, Verstecken (auf Informationsfrontend)

|tbl_partnership |Zuweisung eines Partnerschaftstypes (1:n) zu tbl_institute |Anlegen (implizit mit Vertrag)

|tbl_partnership_type |Definition unterschiedliche Abkommenstypen |-

|tbl_mobility_agreement |Vertragsinformationen, verweist auf den Mentor und den Vertragstyp / Hochschule in _tbl_partnership_ |Anlegen, Ändern, Deaktivieren

|tbl_mobility_agreement_x_course |optionale Beschränkungen der Anzahl der Incoming / Outgoing pro Vertrag und Studiengang

Bsp.: Vertrag der Fakultät Informatik/Mathematik für 7 Studenten;
Incoming/Outgoing -> davon dürfen nur 3 Wirtschaftsinformatiker, 2 Medieninformatiker und 2 Verwaltungsinformatiker sein. |Anlegen, Ändern, Deaktivieren

|new_tbl_course |Kurse der HTW, genutzt von _tbl_mobility_agreement_x_course_ und der Statistik |-

|tbl_exchange_type |Definition der Art des Austausches z.B. Erasmus, Promos, Freemover (Verwendung für die Statistik genutzt) |-

|tbl_exchange |anonymisierte Daten von Incoming / Outgoing Studenten | Import von Excel Datei zum Hinzufügen von Datensätzen
|===
// end::explain_tables[]

TIP: Für eine detaillierte Anzeige der Tabellen betrachten Sie bitte die mitgelieferte SQL Backup Datei. Diese ist als Text lesbar und bildet die gesamte Struktur mitsamt Kommentaren ab.

NOTE: Um Probleme mit Modifikationen von Stammdaten zu vermeiden, ist allein dem Super-User das Löschen fehlerhafter oder nicht mehr benötigter Datensätze erlaubt. Der Nutzen dieser Funktion sollte jedoch die Ausnahme bilden und nicht die Regel.

==== Views
Für das Informationsfrontend müssen passende Views für jede jeweilige Tabelle (außer für _tbl_exchange_ und _tbl_exchange_type_) eingerichtet werden. In diesen dürfen nur aktive Verträge angezeigt werden.

==== Verwaltung der Datenbank
Das Rechenzentrum der HTW Dresden betreut/pflegt die MarieDB.

=== Webserver

==== Aufbau
Dank Bereitstellung des Laborbereichs Informatik der HTW Dresden, fungiert eine virtuelle Maschine als Webserver. Das Backend läuft dort in Python während das Frontend über HTML, CSS sowie Javascript läuft.

==== Authentifizierung im Browser

Vor dem Zugriff auf die Webanwendung muss sich der User per Login authentifizieren. Die Anmeldedaten (hier Admin-Login) entsprechen den vom Rechenzentrum bereitgestellten Nutzern der Datenbank, wodurch die Lese-/Schreibrechte über die Datenbank geregelt sind.

==== Darstellung

Das User-Interface hat das Ziel intuitiv nutzbar zu sein aber auch vertraut auf die Stabstelle zu wirken. Die Vorgruppe hat hier einen sehr guten Prototypen erstellt, weswegen wir diesen übernommen und erweitert haben.

* Das Farbschema der gesamten Anwendung beschränkt sich auf einen weißen Hintergrund, schwarz für Standardschrift, die Navigationsleiste und die Tabellenlinien, blau und grau für Buttons sowie rot für wichtige Schrift
* Die Navigationsleiste zeigt die wichtigsten Links zu den Ansichten der Fakultäten, Hochschulen, Länder, Mentoren und Studiengänge und ist schwarz mit weißer bzw grauer Schrift
* Standardmäßig sind die Reiterüberschriften dunkelgrau und werden erst beim Mouseover hovern heller hervorgehoben
* Alle Buttons haben abgerundete Ecken
* Buttons zum Anlegen neuer Datensätze haben keine Hintergrundfüllung, sind blau umrandet und haben eine ebenfalls blaue Schrift
* Der Zurücksetzenbutton auf der Hauptseite hat keine Hintergrundfüllung und ist grau umrandet mit grauer Schrift
* Die Daten der verschiedenen Hochschulen etc. werden als Tabelle auf den jeweiligen Seiten dargestellt
* In den Tabellen der Hochschulen und Mentoren wird für jede Zeile und damit jede Hochschule bzw. jeden Mentoren ein Button zum Bearbeiten für jeden Datensatz von Hoschschulen und Mentoren
* Für den Admin-Login wird zusätzlich neben dem Bearbeiten-Button ein weiterer Button zum löschen eines Datensatzes angezeigt. Dieser ist nur für den Admin-Login sichtbar
* Auf der Seite der Hochschulen befinden sich oberhalb der Seite Dropdowns zum Filtern der Inhalte nach: Land, Fakultät, Anzeige auf HTW-Seite, Inaktive/aktive/gesamte Vertäge, Vertragstyp sowie der Sortierung aufsteigend oder absteigend alphabetisch
* Ebenfalls auf der Seite der Hochschule sind die Infos der Hochschule sowie der Verträge nebeneinander angeordnet in jeweiligen Fenster, um eine gewisse einfache Übersichtlichkeit zu bieten und die Klickarbeit zu meiden 
* Auf der Seite der Mentoren befindet sich am Seitenanfang ein Eingabefeld, welches die Textsuche über den Namen eines Mentoren ermöglicht
* Über den Bearbeiten- oder Hinzufügen-Button auf den Seiten der Mentoren und Hochschulen öffnet sich jeweils ein Formular mit Eingabemöglichkeiten für die jeweiligen Daten der Datensätze. 
* Die Formularansicht wurde mit Eingabefelder und Labels versehen, um die einfache Zuordnung durch einen Nutzer zu garantieren. Der Speichern-Button ist auch hier Blau hinterlegt, um die Funktion zu verdeutlichen.
* Die Pflichtfelder in den Eingabeformularen sind jeweils rot markiert

==== Validierung von Daten

* Im Formular zum anlegen einer neuen Hochschule können Daten nur dann gespeichert werden, wenn bereits eine englische Bezeichnung eingetragen wurde. Bis dahin ist der Speichern-Button inaktiv.

* Die letzte Instanz der Validierung stellt die Datenbank selbst dar; dort werden nicht valide Formate in einer SQL-Query abgewiesen.

=== Synchronisation

* Es werden beim Öffnen der Webanwendung die aktuellsten Daten geladen und diese werden dem Nutzer angezeigt

//* Tätigt der Nutzer Eingaben zum Anlegen oder Ändern von Datensätzen werden die Eingaben zunächst Zwischengespeichert und erst beim drücken des Speicherbuttons persistiert || Anmerkung Kev: erste Teil bisher irgendwie nicht .-.

=== Schnittstelle zwischen Front- und Backend

Durch POST-Requests wird die Übergabe von Daten aus dem Frontend ins Backend geregelt. Verschiedene Javascript-Skripte werten, je nach Anfrage, die Nutzerdaten aus und senden sie an das Backend. Die einzelnen Parameter der Anfrage werden dort ausgewertet und weiterverarbeitet. Geht es um die reine Darstellung der Webseiten, so nutzt der Client, GET-Anfragen um die entsprechende Website vom Server zurückgeliefert zu bekommen.

Um eine einfache Verarbeitung, der vom Server geschickten Daten, im Frontend vornehmen zu können, haben wir uns für die Methode der Vorgruppe entschieden, eine übermittlung per JSON-Datei. Es gibt eine einfache Möglichkeit Pythoneigene Datentypen in eine JSON-Datei zu packen, somit ist der Clientseitige Zugriff auf die Daten ähnlich wie auf dem Server.

== Graphische Designaspekte


Grafische Designaspekte beschreiben Entwurfsentscheidungen, die direkten Einfluss auf die Darstellungsweise einzelner Systemkomponenten für den Benutzer haben.

Da der Kunde bereits vorher mit Microsoft Access gearbeitet hat und vertraut war, wurde hierbei der Prototyp stark an jenes Programm angelehnt, um einen einfachen Übergang in eine neue, aber vertrautwirkende Umgebung für den Nutzer zu ermöglichen. Die vorhandenen Daten werden größtenteils durch Tabellen dargestellt. Formulare dienen dem Anlegen oder der Bearbeitung von Datensätzen durch den Nutzer. Generell soll möglichst zusätzliche Arbeit, sei es Scrollen oder zusätzliche Klicks, gemieden werden, wodurch diverse Funktionalitäten und Ansichten auf ein weites, kompaktes Fenster komprimiert wurden. Die Schriftart ist einfach und breit dargestellt, wodurch sie gut und angenehm zu lesen ist.

Die Liste von Hochschulen, Ländern, Vertragstypen etc. werden beim Laden der Seite durch Javascript-Skripte geladen zusätzlich bei der Auswahl eines Filters aktualisiert. Sie sind in einer Tabelle angeordnet.

Die Bearbeitungsformulare der Hochschule werden direkt neben der Hochschulliste dargestellt, um zusätzliche Klickarbeit zu vermeiden aber auch einer besseren Übersicht zuliebe.


// end::include_development[]