= Checkliste für Anforderungen: {project-name}
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]

== Website allgemein
//Reiter Hochschule
[%header, cols="3,1,1"]
|===
|Anforderungsspezifikationen |Status | Kommentar |
Filterung nach Land, Hochschule und Vertragstyp| in Bearbeitung |Untere Filterzeile weg, Filter-Rücksetzen führt teilweise zu Aufhängen der Website (Probleme im Code) |
 funktionsfähiger LogOut-Button| erledigt | / |
 Löschen von Inhalten| / | Superuser oder Passwortfunktion (nur Frau Terpe Berechtigungen geben) 
|===


== Rechtes Fenster

[%header, cols="3,1,1"]
|===
|Anforderungsspezifikationen |Status | Kommentar |
Extra-Bearbeitungsfenster als Alternative, da Fokus auf Vertrags Fenster liegt (komprimieren, Namen ausführlicher anzeigen) | abgelehnt von uns | 
Erasmus und Hochschulpartnerschaften Anzahl weg | Layout des Fensters anpassen | erledigt | / 
|===

== Mittlers Fenster

[%header, cols="3,1,1"]
|===
|Anforderungsspezifikationen |Status | Kommentar |
eine Ansprechperson + eine Extra-Ansprechperson pro Hochschule eingetragen und ausgelesen werden können| erledigt | laut Spezifikation nur Name, Vorname und Email|
Name der Ansprechperson kann in den Hintergrund rücken, wichtig sind hierbei die Mail-Adressen, welche sofort sichtbar sein sollen| erledigt |Bei Ansprechperson nicht nötig (wechselt auch zu offen) → nur International Office benötigt |
Name von Partnerhochschule in Englisch und in Originalsprache darstellen + ERASMUSCODE |erledigt|laut Frau Terpe soll es ein Popup-Fenster für Notizen geben, obwohl Notizfeld bereits vorhanden ist und Kunde eigentlich streng gegen Popup-Fernster ist
|===

== Linkes Fenster

[%header, cols="3,1,1"]
|===
|Anforderungsspezifikationen |Status | Kommentar |
direktes Auswählen von Universitäten per Anklicken | erledigt | ebenfalls Format angepasst, weniger Zeilenumbrüche
|===

== Fakultät
//Reiter Fakultät

[%header, cols="3,1,1"]
|===
|Anforderungsspezifikationen |Status | Kommentar |
Möglichkeit zum Bearbeiten, Anlegen und Löschen von Fakultäten| wird nicht umgesetzt |Aufgabe SHK
|===

== Mentoren
//Reiter Metoren

[%header, cols="3,1,1"]
|===
|Anforderungsspezifikationen | Status | Kommentar |
Bei Mentor Name: Feld größer, da viele Titel Länderauswahl/Hochschulauswahl soll sich nicht schon bei Veränderung d. Verträge zurücksetzen| / |Mentoren: Mentor suchen größer, Filtern nach Fakultät, Mentor im Detail: Fakultät stimmt nicht überein 
|===

== Berichte
//Reiter Berichte

[%header, cols="3,1,1"]
|===
|Anforderungsspezifikationen |Status | Kommentar |
Erstellen von Berichten für Vertragstypen, Fakultäten und Länder | Iteration 5 geplant | in PDF ausdruckbar sein
|===

== Nice To Have

[%header, cols="3,1,1"]
|===
|Anforderungsspezifikationen |Status | Kommentar |

Button „Partnerhochschule hinzufügen“ ganz nach unten (weil nur selten)| | |

Notizen zum Aufklappen: Info über aktuelle Situation (benötigt mehr Platz → Russland Partnerschaft ruht)| /| Notizfeld einfach vergrößern, Kunde ist eigentlich gegen Popup-Felder|

Bei Vertrag: Fakultät ändern eher unnötig, neuen Vertrag nicht neu Anlegen (nach unten)| | ??? Frau Terpe möchte Button ganz weghaben ???|

Fakultäten evtl. zusammenlegen → Vererbung von Verträgen| geht nicht| nicht umsetzbar, Merge von Kunde vorgeschlagen ist aber über einfaches dropdown menu schon implementiert |

Länderübersicht ok: bis auf Neues Land hinzufügen fehlt| | |

Verträge / Partnerschaften der Fakultät Wirtschaftswissenschaften (7700) sollen auf der externen Website nach Studiengängen gefiltert werden können| /| SHK|

Kompatibilität des Systems mit dem Typo-3-PlugIn| erledigt | SHK 
|===