= System-Wide Requirements: {project-name}
//Max Listner <max.listner@htw-dresden.de>; Marlene Pannoscha <marlene.pannoscha@htw-dresden.de>; Alessandra Ruff <alessandra.ruff@htw-dresden.de>; Dilara Eichler   <dilara.eichler@htw-dresden.de>; Kevin Freund <kevin.freund@htw-dresden.de>; Robert Alexander Pfund <robertalexander.pfund@htw-dresden.de>; Karl Gustav Langer <karlgustav.langer@htw-dresden.de>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Einführung
In diesem Dokument werden die systemweiten Anforderungen für das Projekt I2_Webuserinerface_für_Datenbankverwaltung spezifiziert. Die Gliederung erfolgt nach der FURPS+ Anforderungsklassifikation:

* Systemweite funktionale Anforderungen (F),
* Qualitätsanforderungen für Benutzbarkeit, Zuverlässigkeit, Effizienz und Wartbarkeit (URPS) sowie
* zusätzliche Anforderungen (+) für technische, rechtliche, organisatorische Randbedingungen

//NOTE: Die funktionalen Anforderungen, die sich aus der Interaktion von Nutzern mit dem System ergeben, sind als Use Cases in einem separaten Dokument festgehalten. [hier ggf. Verweis einfügen]


== Systemweite funktionale Anforderungen
//Angabe von system-weiten funktionalen Anforderungen, die nicht als Use Cases ausgedrückt werden können. Beispiele sind Drucken, Berichte, Authentifizierung, Änderungsverfolgung (Auditing), zeitgesteuerte Aktivitäten (Scheduling), Sicherheit / Maßnahmen zum Datenschutz
* SWFA-1: Das System muss jegliche Daten bezüglich den Hochschulpartnerschaften speichern.
** Zur Überprüfung wird die Seite nach dem Speichern neu geladen.
* SWFA-2: Zugriff auf das Verwaltungsfrontend dürfen lediglich autorisierte Mitarbeiter/-innen der Stabstelle Internationales haben.
** Zur Überprüfung wird versucht, das Verwaltungsfrontend außerhalb des HTW-Netzes zu öffnen sowie sich mit falschen Login-Daten anzumelden.


== Qualitätsanforderungen für das Gesamtsystem
//Qualitätsanforderungen repräsentieren das "URPS" im FURPS+ zu Klassifikation von Anforderungen

=== Benutzbarkeit (Usability)
//Beschreiben Sie Anforderungen für Eigenschaften wie einfache Bedienung, einfaches Erlernen, Standards für die Benutzerfreundlichkeit, Lokalisierung (landesspezifische Anpassungen von Sprache, Datumsformaten, Währungen usw.)
* NFAU-1: Das System sollte benutzerfreundlich formatiert und bedienbar sein, für kleine als auch größere PC-Monitore.
** Zur Überprüfung werden PC-Monitore verschiedensten Größen bedient.
* NFAU-2: Das Verwaltungsfrontend sollte auf verschiedenen Betriebssystemen mit unterschiedlichen Browsern laufen.
** Zur Überprüfung wird das Verwaltungsfrontend auf Rechner mit den gängigen Betriebssystemen und deren Browsern aufgerufen.

=== Zuverlässigkeit (Reliability)
// Zuverlässigkeit beinhaltet die Fähigkeit des Produkts und/oder des Systems unter Stress und ungünstigen Bedingungen am laufen zu bleiben. Spezifizieren Sie Anforderungen für zuverlässige Akzeptanzstufen, und wie diese gemessen und evaluiert werden. Vorgeschlagene Themen sind Verfügbarkeit, Häufigkeit und Schwere von Fehlern und Wiederherstellbarkeit.
* NFAR-1: Beim Abruf eines vorherigen Zustandes der Datenbank, muss das Verwaltungsfrontend weiterhin funktionieren.
** Zur Überprüfung werden Backups der Datenbank hochgeladen.
* NFAR-2: Es besteht die Möglichkeit, dass Verwaltungs- und Informationsfrontend gleichzeitig Daten abrufen können.
** Zur Überprüfung wird an einem Rechner im Verwaltungsfrontend ein bestehender Datensatz modifiziert, während dieser parallel an einem anderem Rechner im Informationsfrontend angesehen wird.
* NFAR-3: Das System muss paralleles Lesen und Schreiben im Verwaltungsfrontend unterstützen. (Multi-User-System)
** Zur Überprüfung werden jeweils zwei verschiedene Login-Sessions laufen, um einerseits einen Datensatz zu lesen und andererseits parallel dazu einen Datensatz zu schreiben.


=== Effizienz (Performance)
// Die Performanz Charakteristiken des Systems sollten in diesem Bereich ausgeführt werden. Beispiele sind Antwortzeit, Durchsatz, Kapazität und Zeiten zum Starten oder Beenden.
* NFAP-1: Das Wechseln von Seiten innerhalb des Verwaltungsforntends sollte innerhalb maximal 3 Sekunden stattfinden.
** Zur Überprüfung werden Seitenaufrufe per Skript simuliert und dabei auf deren Antwortzeit gemessen.
* NFAP-2: Datenbankrelevante Funktionen sollten möglichst schnell, maximal in 2 Sekunden, ausführbar sein.
** Zur Überprüfung werden Funktionen per SQL-Befehle ausgeführt und dabei auf deren Ausführungszeit gemessen.

=== Wartbarkeit (Supportability)
// Dieser Bereich beschreibt sämtliche Anforderungen welche die Supportfähigkeit oder Wartbarkeit des zu entwickelnden Systems verbessern, einschließlich Anpassungsfähigkeit und Erweiterbarkeit, Kompatibilität, Skalierbarkeit und Anforderungen bezüglich der System Installation sowie Maß an Support und Wartbarkeit.
* NFAS-1: Übersichtliche und ausführliche Hinweise/Dokumentation, um Erweiterbarkeit zu erleichtern.
* NFAS-2: Mögliche Erweiterbarkeit des Systems
** Zur Überprüfung wird im Verlauf des Projektes das System stetig um neue Funktionen erweitert.

== Zusätzliche Anforderungen

=== Einschränkungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Kompatibilität zwischen dem System und der bestehenden Datenbankstruktur
* strikte Kompetenzvergabe an jewilige Rolle

=== Organisatorische Randbedingungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* ausführliche und aussagekräftige Dokumentation
* verständliches Näherbringen des Systems an die Stabstelle

=== Rechtliche Anforderungen
//Angaben ergänzen, nicht relevante Unterpunkte streichen oder auskommentieren
* Da die Datenbank, abgesehen von ohnehin schon frei zugänglichen Daten der Mentoren, keine personenbezogenen Daten abspeichert (sondern nur Statistiken) ist die Anwendung datenschutzrechtlich unbedenklich.
