= Architecture Notebook: {project-name}
Vorname Nachname <email@domain.org>; Vorname2 Nachname2 <email2@domain.org>; Vorname3 Nachname3 <email3@domain.org>
{localdatetime}
include::../_includes/default-attributes.inc.adoc[]
// Platzhalter für weitere Dokumenten-Attribute


== Zweck
Dieses Dokument beschreibt die Philosophie, Entscheidungen, Nebenbedingungen, Begründungen, wesentliche Elemente und andere übergreifende Aspekte des Systems, die Einfluss auf Entwurf und Implementierung haben.

//Hinweise: Bearbeiten Sie immer die Abschnitte 2-6 dieser Vorlage. Nachfolgende Abschnitte sind empfohlen, aber optional und sollten je nach Umfang der künftigen Wartungsarbeiten, Fähigkeiten des Entwicklungsteams und Bedeutung anderer architektureller Belange.

//Anmerkung: Die Architektur legt wesentliche EINSCHRÄNKUNGEN für den Systementwurf fest und ist ein Schlüssel für die Erfüllung nicht-funktionaler Eigenschaften!


== Architekturziele und Philosophie
//Hinweise: Beschreiben Sie die Philosophie der Architektur, d.h. den zentralen Ansatz für ihre Architektur. Identifizieren Sie alle Aspekte, die die Philosophie beeinflussen, z.B. komplexe Auslieferung Aspekte, Anpassung von Altsystemen oder besondere Geschwindigkeitsanforderungen. Muss es besonders robust sein, um eine langfristige Wartung und Pflege zu ermöglichen?

//Formulieren Sie eine Reihe von Zielen, die die Architektur in ihrer Struktur und ihrem Verhalten erfüllen muss. Identifizieren Sie kritische Fragen, die von der Architektur adressiert werden müssen, z.B. besondere Hardware-Abhängigkeiten, die vom Rest des Systems isoliert werden sollten oder Sicherstellung der Funktionsfähigkeit unter besonderen Bedingungen (z.B. Offline-Nutzung).
Die Absicht der Systemarchitektur ist die Erweiterung der bisher bereitgestellten Webanwendung, welche die Organisation und Verwaltung der Hochschulpartnerschaften erleichtern soll. Den Nutzer/-innen soll (eine userfreundliche) Nutzung im Browser auf Rechnern (Laptop, Notebook, Desktop-Rechnern) gewährt werden, ausgeschlossen sind mobile Endgeräte.
 
Die Erreichbarkeit des Systems beschränkt sich auf die Arbeitszeiten der Stabstelle Internationales, diese ((bezieht)) sich auf werktags 8h, 7-15 Uhr. Außerhalb der Zeit besteht keine Verpflichtung der Arbeitszeit.
Die bisherige MariaDB und Access Datenbank werden als Datenbanken genutzt, diese werden vom Rechenzentrum bereitgestellt. Die bisherige Software setzt sinngemäß auf der MariaDB auf, jedoch bedarf es an Ergänzung bei der Kommunikation zwischen den Inhalten und dem Frontend. Das Backend soll so erweitert werden, dass das Verwaltungsfrontend die Statistiken der Auslandsaktivitäten von Studierenden darstellt. 


== Annahmen und Abhängigkeiten
//[List the assumptions and dependencies that drive architectural decisions. This could include sensitive or critical areas, dependencies on legacy interfaces, the skill and experience of the team, the availability of important resources, and so forth]

 
. Nutzer/-innen sind Mitarbeiter/-innen der Stabsstelle Internationales
. Nutzer/-innen befinden sich, mit einer stabilen Internetverbindung mit genügend Bandbreite und einem modernen Browser, im Netz der HTW Dresden
. Jede/r Nutzer/-innen benutzt einen HTML5-fähigen Browser und erlaubt JavaScript.
. die eingesetzten Frameworks werden auch in Zukunft unterstützt
. Wir gehen davon aus, dass die Server der Informatik Fakultät stabil laufen, um sicherzustellen, dass unser Online-Tool stets erreichbar ist.

. Abhängigkeit vom Rechenzentrum der HTW
.. Der von uns genutzte Server läuft über eine virtuelle Maschine, welche vom Rechenzentrum bereitgestellt wird, und muss in der Woche von 7-15 Uhr erreichbar sein
.. Die Administration unserer Datenbank erfolgt über das Rechenzentrum, weswegen ein/e verantwortliche/r Mitarbeiter/-in die Verwaltung der Logins übernehmen muss 
. Abhängigkeit von Vorkenntnissen der Teammitglieder
.. Die Teammitglieder haben angeeignetes Wissen bezüglich der Webentwicklung mittels Python, Html sowie JavaScript (jQuery)
. Abhängigkeit von Einsatzbereitschaft und Instandhaltung der genutzten Frameworks sowie externen Komponenten
.. Die eingesetzten Frameworks (Flask, jQuery) müssen vom Hersteller, um deren Funktionen einwandfrei nutzen zu können, regelmäßig gewartet werden.

== Architektur-relevante Anforderungen
//Fügen Sie eine Referenz / Link zu den Anforderungen ein, die implementiert werden müssen, um die Architektur zu erzeugen.

*Funktional*
 
* SWFA-1: Das System muss jegliche Daten bezüglich der  Hochschulpartnerschaften speichern
* SWFA-2: Zugriff auf das Verwaltungsfrontend dürfen lediglich autorisierte Mitarbeiter/-innen der Stabstelle Internationales haben. 

*Zuverlässigkeit*

* NFAR-1: Beim Abruf eines vorherigen Zustandes der Datenbank muss das Verwaltungsfrontend weiterhin funktionieren.
* NFAR-2: Es besteht die Möglichkeit, dass Verwaltungs- und Informationsfrontend gleichzeitig Daten abrufen können.
* NFAR-3: Das System muss paralleles Lesen und Schreiben im Verwaltungsfrontend unterstützen (Multi-User-System).
 
*Effizienz (Performance)*

* NFAP-1: Das Wechseln von Seiten innerhalb des Verwaltungsforntends sollte innerhalb von maximal 3 Sekunden stattfinden.
* NFAP-2: Datenbankrelevante Funktionen sollten möglichst schnell, innerhalb maximal 2 Sekunden, ausführbar sein.
* Erweiterbarkeit der Systemfunktionalität

*Benutzbarkeit*

* NFAU-1: Das System sollte benutzerfreundlich formatiert und bedienbar sein, für kleine als auch größere PC-Bildschirme.
* NFAU-2: Das Verwaltungsfrontend sollte auf verschiedenen Betriebssystemen mit unterschiedlichen Browsern laufen.



== Entscheidungen, Nebenbedingungen und Begründungen
//[List the decisions that have been made regarding architectural approaches and the constraints being placed on the way that the developers build the system. These will serve as guidelines for defining architecturally significant parts of the system. Justify each decision or constraint so that developers understand the importance of building the system according to the context created by those decisions and constraints. This may include a list of DOs and DON’Ts to guide the developers in building the system.]

Das Team hat sich darauf geeinigt, den Prototypen/das Modell der vorherigen Gruppe fortzuführen. Dadurch sind vorherige Bemühungen nicht völlig umsonst gewesen. Des Weiteren besteht dadurch eine Basis, durch welche man nicht von Grund auf Neues schaffen muss.

* Nutzen des Vorgängermodells
** funktionierende, bestehende Basis ermöglicht Zeitersparnis
** Dokumentation ermöglicht einfachere Einarbeit

* Nutzen/Aneignen der vorher genutzen Programmiersprachen
** zum Fortführen/Überarbeiten des Vorgängermodells
** bereits gut ausgewählte und weit verbreitete Programmiersprachen

Dadurch, dass das Rechenzentrum der HTW Dresden den Vorgängern eine Datenbank, in Form einer MariaDB, bereits zur Verfügung gestellt hat, muss das Team keine neue Datenbank erstellen.
 
* Verwendung der MariaDB
** Möglichkeit zum Ändern der Datensätze außerhalb des Verwaltungsfrontend
** Backups auf den Servern des Rechenzentrums
** Aufruf durch phpMyAdmin
** starke Ähnlichkeit zu MS SQL, mit dem eine Vielzahl der Gruppenmitglied bereits Erfahrung hat


== Architekturmechanismen
//https://www2.htw-dresden.de/~anke/openup/core.tech.common.extend_supp/guidances/concepts/arch_mechanism_2932DFB6.html[Doku "Concept: Architectural Mechanism"]
//[List the architectural mechanisms and describe the current state of each one. Initially, each mechanism may be only name and a brief description. They will evolve until the mechanism is a collaboration or pattern that can be directly applied to some aspect of the design.]

//Beispiele: relationales DBMS, Messaging-Dienste, Transaktionsserver, Webserver, Publish-Subscribe Mechanismus

//Beschreiben Sie den Zweck, Eigenschaften und Funktion der Architekturmechanismen.

. Architekturmechanismus 1
. Architekturmechanismus 2


== Wesentliche Abstraktionen
//[List and briefly describe the key abstractions of the system. This should be a relatively short list of the critical concepts that define the system. The key abstractions will usually translate to the initial analysis classes and important patterns.]


== Schichten oder Architektur-Framework
//[Describe the architectural pattern that you will use or how the architecture will be consistent and uniform. This could be a simple reference to an existing or well-known architectural pattern, such as the Layer framework, a reference to a high-level model of the framework, or a description of how the major system components should be put together.]


== Architektursichten (Views)
//C4 Modell
//[Describe the architectural views that you will use to describe the software architecture. This illustrates the different perspectives that you will make available to review and to document architectural decisions.]

Folgende Sichten werden empfohlen:

=== Logische Sicht
//Beschreibt die Struktur und das Verhalten Systemteilen, die hohen Einfluss auf die Architektur haben. Dies kann die Paketstruktur, kritische Schnittstellen, wichtige Klassen und Subsysteme sowie die Beziehungen zwischen diesen Elementen enthalten. Zudem sollten die physische und logische Sicht persistenter Daten beschrieben werden, wenn es diesen Aspekt im System gibt. Dies ist ein hier dokumentierter Teilaspekt des Entwurfs.

=== Physische Sicht (Betriebssicht)
//Beschreibt die physischen Knoten (Rechner) des Systems, der Prozesse, Threads und Komponenten, die in diesen Knoten ausgeführt werden. Diese Sicht wird nicht benötigt, wenn das System in einem einzelnen Prozess oder Thread ausgeführt wird.

=== Use cases
//Eine Liste oder ein Diagramm der Use Cases, die architektur-relevante Anforderungne enthalten.
