= Projektplan: {project-name}


Max Listner
<max.listner@stud.htw-dresden.de>

Alessandra Ruff
<alessandra.ruff@stud.htw-dresden.de>

Dilara Eichler
<dilara.eichler@stud.htw-dresden.de>

Kevin Freund
<kevin.freund@stud.htw-dresden.de>

Robert Alexander Pfund
<robertalexander.pfund@stud.htw-dresden.de>

Karl Gustav Langer
<karlgustav.langer@stud.htw-dresden.de>

Marlene Pannoscha
<marlene.pannoscha@stud.htw-dresden.de>



== Einführung
//Briefly describe the content of the project plan.

Der Projektplan stellt die Grundlage für das Projekt dar. Das Team ist in der Lage sich die einzelnen Punkten als Orientierung zu nutzen und somit eine strukturierte Arbeitsweise aufzubauen.

//auftreten Unklahrheiten bietet der Projektplan ein Hilfestellung um diese zu lösen

== Projektorganisation
//Introduce the project team, team members, and roles that they play during this project. If applicable, introduce work areas, domains, or technical work packages that are assigned to team members. Introduce neighboring projects, relationships, and communication channels. If the project is introduced somewhere else, reference that location with a link.
Das Team SE-Projekt-I2 besteht aus insgesamt sieben Studierenden aus den Studiengängen Wirtschaftsinformatik und Wirtschaftsingenieurswesen.

Die Rollen wurden von den Studierenden wie folgt eingenommen:

[.landscape]

<<<

[%header, cols="2,1,3,2"]
|===
| Rolle
| Team-Mitglied
| Beschreibung der Aufgabe
| Artefakte

| Teamleitung
a|
* Max Listner
* Marlene Pannoscha
a|
* Leitung des Projektes
* Kommunikation/Schnittstelle mit Auftraggeber, Coach, Stakeholder und Gruppe
* Planung der Iterationsschritte
* Kontrolle des Projektvortschrittes
a|
* Proketplan
* Iterationplan
* Vision
//ergänzen

|Analyse
a|
* Max Listner
* Kevin Freund
* Marlene Pannoscha
a|
* Erfassen und genaue Beschreibung von Kundenwüschen- und Anforderungen
* Probleme identifizieren
* Prioritäten festlegen
a|
* Glossary
* System-Wide Requirements
* Use Case Model
* Domänenmodel


|Entwurf
a|
* Robert Alexander Pfund
* Karl Gustav Langer
* Dilara Eichler
a|
* Erstellen eines Systementwurfes
a| 
* Architektur Notebook

|Implementierung
a|
* Karl Gustav Langer
* Alessandra Ruff
* Kevin Freund
* Dilara Eichler
a|
* Implementierung des erstellten Systementwurfes und der wichtigsten Funktionen
a|
* Architektur Notebook

|Testen
a|
* Karl Gustav Langer
* Alessandra Ruff
a|
* Testen der implementierten Funktionen
* Testen der Funktionalitäten des Systems
a|
* Test Cases
|===



== Praktiken und Bewertung
//Describe or reference which management and technical practices will be used in the project, such as iterative development, continuous integration, independent testing and list any changes or particular configuration to the project. Specify how you will track progress in each practice. As an example, for iterative development the team may decide to use iteration assessments and iteration burndown reports and collect metrics such as velocity (completed work item points/ iteration).
Zur Dokumentation dieses Projektes nutzen wir ein GitHub-Repository. Die entsprechenden Dokumente werden mit Visual Studio Code erstellt, bearbeitet und dann ins Repository gepusht bzw. von dort aus gepullt.

Um unser Projekt erfolgreich durchzuführen, nutzen wir die Dokumentvorlagen des Open Unified Process (OpenUP). Aufgaben werden hierbei in Iterationen bearbeitet, welche jeweils 2 Wochen andauern. Die zu erledigenden Aufgaben werden als Issues festgehalten und dem jeweiligen Gruppenmitglied zugewiesen.

Zur Kommunikation wurde Discord und WhatsApp, sowie E-Mails benutzt. Dokumente wurden entweder über Discord oder über GitHub geteilt. Wir haben versucht, unsere Meetings immer in präsenz durchzuführen, was uns mit der Stabsstelle Internationales auch gelungen ist.

== Meilensteine und Ziele
//Define and describe the high-level objectives for the iterations and define milestones. For example, use the following table to lay out the schedule. If needed you may group the iterations into phases and use a separate table for each phase

[%header, cols="1,3a,2,1"]
|===
| Iteration
| Primary objectives +
(risks and use case scenarios)
| Scheduled start or milestone
| Target velocity

| I1
| Analyse des bestehenden Systems
* mit bestehendem System vertraut machen
* Beginnen mit Vision
* Beginnen mit Glossar und Risikoliste
| 28.11.2022 - 11.12.2022
| 15

| I2
| Funktions- und Anforderungsanalyse
* festhalten der Hauptanforderungen an das GUI
* erstellen der wichtigsten UseCases
* erstellen von Wireframes
* erstellen des Domänen-Modells
* ergänzen von Vision, Glossar und Risiokoliste 
| 12.12.2022-25.12.2022
| 15

| I3
|erste Implementierungschritte
* erstellen eines Architektur-Modells
* erstellen eines Prototypen, implementierung der ersten Funktionen
| 2.01.2023 - 15.01.2023
| 16

| I4
|weitere Implementierungschritte
* weitere wichtige Funktionen werden im Prototypen implementiert
* die systemweiten Anforderungen und das Architektur-Modell werden angepasst bzw. vervollständigt
| 16.01.2023 - 27.01.2023 (Projektabgabe)
| 16
|===



== Deployment
//Outline the strategy for deploying the software (and its updates) into the production environment.
Das System wird auf einer vom Rechenzentrum zur Verfügung gestellten virtuellen Maschine betrieben. Um neue Funktionen zu testen und den Verlust von Daten zu verhindern, nutzen wir eine lokale Maria-DB.


== Erkenntnisse (Lessons learned)
//List lessons learned from the retrospective, with special emphasis on actions to be taken to improve, for example: the development environment, the process, or team collaboration.
Wir haben während des Semesters gelernt, dass eine offene, schnelle, sowie ehrliche Kommunikation, sowohl mit dem Kunden als auch im Team, der Schlüssel für ein erfolgreiches Projekt sind. Fehler bzw. Probleme sollten so schnell wie möglich kommuniziert werden, um eine gleichmäßig schnelle Lösung zu finden. Durch Kommunikation wird ein besseres Verständniss des Aufgabenbereiches, sowie eine klare Abfolge von Aufgaben / Aktionen erreicht.

Ein weiterer Punkt ist Zeitmanagement. Durch das Vorrausplanen von Meetings und bevorstehenden Aufgaben, lassen sich diese viel einfacher und effizienter bearbeiten, ohne dabei in Zeitdruck zu geraten oder vor einem Abschnitt zu stehen, in dem nicht klar ist, was getan werden muss.

Auch die Arbeit mit dem OpenUP haben, welche Anfangs als umständlich angesehen wurde, wurde während des Projektes verstanden. Dieser hilft nicht nur, Aufgaben zu organisieren und Dokumente anzulegen, sondern auch bei der Organisation des Projektes im Allgemeinen. Durch die Dokumentation nach dem OpenUP wird sichergegangen, dass keine Informationen verloren gehen, sowie dass man den Überblick über zu erledigende Aufgaben behält.
