= Projektbericht: {project-name}
include::../_includes/default-attributes.inc.adoc[]
:doctype: book
Marlene Pannoscha, Kevin Freund

== Webuserinterface für Datenbankverwaltung (I2)

== Projektplanung

=== Ausgangssituation in SE II
==== Aufgabenstellung und Auftraggeber
Die Stabsstelle Internationales (SI) der HTW Dresden waren Auftraggeber:innen des Projektes "I2 Webuserinterface für Datenbankverwaltung". Die HTW Dresden kooperiert weltweit mit über 170 Hochschulen im Rahmen von Hochschulvereinbarungen bzw. im Rahmen des EU-Programms Erasmus+. Diese vielfältigen Kontakte bilden die Grundlage sowohl für die wissenschaftliche Zusammenarbeit in Lehre und Forschung als auch für den Austausch von Studierenden und Hochschullehrern. Um diese Informationen zu Kontakten und Partnerschaften zu pflegen, sei es Institut, Art der Vereinbarung, Kontakte, Mentoren, etc., nutzen Sie aktuell eine MS Access Datenbank, welche jedoch zu aufwändig und veraltet sei. Der Auftrag des Projektteams I2 war es, den Prototypen der Webanwendung ihrer Vorgängergruppe, welcher die Verwaltung jener Daten vereinfachen soll, zu überarbeiten, zu erweitern und fertig zu stellen.

==== Situation Semesterbeginn
Im WS22/23 wurden die Inception- und Elaborationsphase bereits abgeschlossen (Softwarte Engineering I). Des Weiteren wurden im vorherigen Semester bereits zwei Funktionen implementiert.

==== Teamaufstellung
Zu Beginn des Pojektes bestand das Team aus 7 Mitgliedern (SE I), aus sechs Wirtschaftinformatikstudenten:innen und einem Wirtschaftsingenieurstudent. Zu Beginn des SS23 bestand das Team in Software Engineering II hingegen nur noch aus 6 Mitgliedern, durch das geplante Ausscheiden des Wirtschaftsingenieurs. 

=== Projektorganisation
==== Team
Im vorherigen Semester, während SE I, wurde schnell klar, dass ein Projekt solchen Umfanges eine Menge Vertrauen, ein hohes Maß an Initiative und vor allem festen Zusammenhalt untereinander benötigt. All dies wurde glücklicherweise in SE I aufgewiesen, weswegen es umso wichtig war das alles im Verlauf des Projektes beizubehalten. Um dies unter anderem zu ermöglichen gab es regelmäßige Teammeetings, bei aufkommenden Fragen konnte man immer im Team um Rat bitten und bei Problemen wurde einem stets geholfen.

==== Rollenverteilung
Das Team empfand, dass die Rollen eher einer Art Verantwortungsbereich entsprachen statt einer festen Zuordnung zu einem Gebiet, weswegen bei der Rollenverteilung darauf geachtet wurde, dass sich ein Mitglied um die Verantwortung des Gebietes kümmert, dieser ein Back-Up/Stellvertreter hat und die anderen Mitglieder bei den jeweiligen Aufgaben zur Seite stehen, wodurch eine gute Mischung aus Rollenspezialisierung, Einbringen verschiedener Kenntnisse und Verteilung von Kapazitäten ermöglicht wurde. +
Die Verantwortungsaufteilung lautet wie folgt:

* Project-Manager: Marlene Pannoscha (MP), Kevin Freund (KF)
* Analyst: Kevin Freund, Marlene Pannoscha 
* Architect: Dilara Eichler (DE), Kevin Freund
* Developers: Alessandra Ruff (AR), Robert Alexander Pfund (RP)
* Tester: Robert Alexander Pfund, Dilara Eichler
* Deployment Engineer: Alessandra Ruff
* Technical Writers: Karl Gustav Langer (KL)

_Ehemals mit Max Listner (ML), als Project-Manager und Analyst._ +
Die genauere Mitgliedereinteilung zu einem jeweiligem Gebiet befindet sich in der Rollenübersicht.

=== Ablauf der Kommunikation unter Verwendung eingesetzter Tools

=== Dokumentation und eigesetzte Tools

=== Way of Working

== Projektdurchführung

=== SE I

=== SE II

==== Start in das Neue Semester (Datum ergänzen)
==== Vorbereitung auf die Entwicklung
==== Entwicklung vorantreiben
==== System abschließen um Kunden Inkremente präsentieren
==== Systemoptimierung und Übergabe an den Kunden

== Projektergebnisse
// Beispiel von Use Cases
=== Softwaresystem
=== Fehlerbehebung
//=== Begründung für das Nichterfüllen von Zielen
=== Reflexion der Teammitglieder

==== Marlene Pannoscha
//Text

<<<

==== Dilara Eichler
//Text

<<<

==== Alessandra Ruff
Die Arbeit an unserem Software-Engineering-Projekt hat mein Wissen und meine Fähigkeiten in verschiedenen Bereichen erweitert. Das Projekt konzentrierte sich auf die Erstellung von einer Web-Benutzeroberfläche für die Datenbankverwaltung der Stabstelle Internationales an der HTW Dresden. Um einen sinnvollen Beitrag zu leisten, musste ich mich intensiv mit verschiedenen Technologien der Webprogrammierung und des Datenbankmanagements auseinandersetzen.

Eine der größten Herausforderungen bestand darin, mich in den Code der Vorgängergruppe einzuarbeiten. Als jemand mit wenig Erfahrung in Webtechnologien wurde ich in eine immense Menge unbekannten Codes geworfen, den ich verstehen und in seine Wirkung und Zusammenhänge einordnen musste. Ich musste mich also mit Frontend-Technologien wie HTML, CSS und JavaScript vertraut machen, um die Benutzeroberfläche zu gestalten, ohne dabei die dahinterliegenden Funktionen zu beeinträchtigen.

Neben den technischen Herausforderungen stellte das Projektmanagement, insbesondere die Dokumentation meiner eigenen Entwicklungsschritte am Anfang, eine größere Hürde dar. Mit der Zeit erkannte ich jedoch, wie wichtig diese Schritte sind, um erfolgreich an einem Projekt zu arbeiten. Die Dokumentation gewährleistete, dass ich mich an Deadlines hielt, einen kontinuierlichen Arbeitsfluss aufrechterhielt und klar strukturierte Ziele festlegte, um nicht vom eigentlichen Thema abzukommen.

Der wohl wichtigste Aspekt unseres Projekts war die Interaktion mit dem Kunden. Da unsere Aufgaben größtenteils optische Anpassungen des Interfaces betrafen, war es sehr wichtig, regelmäßige Treffen mit dem Kunden abzuhalten, um Änderungen und Fortschritte abzustimmen. Mir wurde klar, wie herausfordernd es ist, eine effektive und regelmäßige Kundeninteraktion aufrechtzuerhalten, da sie von zahlreichen externen Einflüssen beeinflusst wird, die nicht immer vorhersehbar sind. Es kam häufig vor, dass neue Anforderungen oder sogar widersprüchliche Erwartungen in kurzer Zeit geäußert wurden, die nicht immer im geforderten Ausmaß umsetzbar waren. Dies erforderte von uns ein hohes Maß an Flexibilität, um angemessen darauf reagieren zu können.

Die Arbeit an diesem Software-Engineering-Projekt hat mir wertvolle Erkenntnisse und wertvolle Erfahrungen beschert. Es war anfangs eine Herausforderung, mit wenig Erfahrung in Webtechnologien in das Projekt einzusteigen und mich in den vorhandenen Code einzuarbeiten.  Durch diese Herausforderungen konnte ich jedoch mein technisches Wissen und meine Fähigkeiten in kurzer Zeit erheblich erweitern. Ich habe gelernt wie wichtig ein strukturiertes Projektmanagement und eine klare Dokumentation sind, um effizient und erfolgreich zu arbeiten. Die Kundeninteraktion stellte sich als entscheidender Faktor heraus, der Flexibilität und Kommunikationsfähigkeiten erforderte, um den Anforderungen und Erwartungen des Kunden gerecht zu werden. Insgesamt war dieses Projekt eine äußerst wertvolle Erfahrung, die mein Verständnis für Softwareentwicklung und Zusammenarbeit vertieft hat und mich für zukünftige Projekte weiter stärkt.


<<<

==== Kevin Freund
Bereits im ersten Semester war mir klar, dass dieses Projekt hier wesentlich anspruchsvoller, aufwendiger und komplexer sein würde als kleinere Schulprojekte von damals. Es war für mich das erste Mal ein Projekt solcher Größe zu bewältigen, welches so langwierig und von so vielen Faktoren abhängig ist.

Ursprünglich war ich für die Analyse und den Entwurf zuständig. Es war interessant zu sehen, wie viel Aspekte vor der eigentlichen Erstellung eines Systems beachtet und ausführlich behandelt werden müssen und wie vielseitig Anforderungen sein können, sei es funktional oder nicht funktional. Hier habe ich gelernt, wie wichtig doch die regelmäßige Kommunikation mit dem Kunden ist, wie oft und schnell sich dessen Anforderungen ändern können, dass dieser sich selbst manchmal noch unsicher darüber ist was genau er eigentlich haben möchte und wie anstrengend er doch manchmal sein kann. Die womöglich größte Herausforderung und Lehre des ersten Projektsemesters war es aber, sich in ein bestehendes System, das unserer Vorgängergruppe, hineinzufinden, dessen Aufbau zu begreifen und Inhalt zu verstehen. Um im Verlauf des Projektes effektiv mitarbeiten zu können, habe ich mich über die Programmiersprachen HTML und JavaScript informiert, was mir definitiv noch nützlich sein dürfte. +
Im Zuge des zweiten Semesters war ich sowohl im Projektmanagement als auch in der Implementierung tätig. Anfangs war beides zugegebenermaßen fordernd und teilweise frustrierend, einerseits die Planung und ausführliche Dokumentation von allem bzw. dem regelmäßigen Überschauen, ob alles stimmt als auch die Instandhaltung der Risikoliste, andererseits die Überarbeitung und Erweiterung des Systems. Letzteres zeigte mir aber deutlich, dass nicht alles sofort funktionieren kann, dass man immer wieder neue Ansätze probieren sollte, dass manches wesentlich komplexer ist und mehr benötigt, dass man vor allem manche Probleme nicht immer alleine bewältigen kann, sondern eher nur im Team. 

Hierbei bin ich wirklich froh darüber, ein so offenes und hilfsbereites Team gehabt zu haben, welches jederzeit für einen da war und niemanden alleine lies. Die Terminplanung war glücklicherweise relativ einfach, wodurch es uns möglich war regelmäßige Teammeetings abhalten zu können. Außerdem gefiel mir, dass, wenn man eine Aufgabe hatte, man sich für diese auch Zeit nahm und man sich um deren Erledigung stets bemühte, was einerseits die Zuverlässigkeit und das Vertrauen untereinander stärkte, andererseits die Arbeit wesentlich angenehmer und kontinuierlicher machte. Es war auch schön mitanzusehen, wie das System Stück für Stück erweitert wurde und mehr Funktionen bot, worauf wir als Team wirklich stolz sein konnten.

Im Kontrast dazu war die Kommunikation mit dem Kunden an manchen Stellen eher frustrierend, sei es die öfters aufkommende Unzuverlässigkeit oder der regelmäßige Ansturm an neuen Anforderungen bzw. Ausfall bereits implementierter Anforderungen, was die Arbeitsweise und den Zeitplan gelegentlich aus der Bahn brachte. Hierbei würde ich in Zukunft dem Kunden gegenüber mehr Deadlines setzen, mehr Druck und Konditionen ansetzen, um allen eine angenehmere Arbeitsatmosphäre bieten zu können. Des Weiteren war die Dokumentation an manchen Stellen etwas sehr aufwendig und übertrieben war. Nichtsdestotrotz sollte diese niemals unterschätzt werden, besonders deren Bedeutsamkeit für Anwender und kommende Entwickler, die dieses System warten oder überarbeiten.

Letztlich kann ich sagen, dass das Projekt definitiv eine Lektion für mein Leben war, dass ich vom hier Gelernten in Zukunft definitiv Gebrauch machen werde und ich über jegliche Erfahrung, die ich hier gesammelt habe, froh bin.

<<<

==== Robert Pfund
Das zweite Semester des Software Engineering Moduls stand von Anfang an unter einem Stern als das letzte. Gerade da wir bereits im ersten Semester aktiv und engagiert an der Anforderungsanalyse gearbeitet hatten, war klar, dass unser Projekt einen größeren Einsatz brauchen würde.

Der nun bereits im dritten Jahr bearbeitete Code hatte ein großes Ausmaß angenommen. Dies sprengte meinen Erfahrungshorizont in Hinsicht auf die Komplexität und Verpflechtungen zwischen den Modulen. Angesichts dieser Problematik waren alle Mitglieder meines Teams eingeschüchtert, doch in unserer Absicht das Projekt erfolgreich abzuschließen, haben wir uns alle tapfer durch dieses Wirr-Warr an Code gekämpft. Im Rahmen dessen wurde mir schnell die Bedeutung von guter Dokumentation klar. Auch wenn unsere Vorgänger den Code im Generellen dokumentiert hatten, war es schwierig ihn zu verfolgen - denn gerade die Verweise waren leider nur schlecht dokumentiert. So musste ich vor allem anfangs manuell Klassen beziehungsweise Methoden suchen um die größeren Abhängigkeiten nachzuvollziehen. Doch gerade das ist eine Herausforderung, von der es nicht unwahrscheinlich ist, dass sie mich auch in meinem späteren Arbeitsleben ereilen wird.

Neben den durch den bereits bestehenden Stand des Projektes entstandenen Problemen, kamen auch die Technologien, welche für die Umsetzung unseres Projektes benötigt wurden, wie ein Sprung ins kalte Wasser. Während Python mir bereits bekannt war, musste ich mich in HTML, CSS und Javascript erst einarbeiten. Gerade in der zweiten Hälfte dieses Semesters gab es allerdings deutliche Erkenntnisfortschritte. Diese waren neben selbst gesammelten Erfahrungen auch durch die theoretischen Erklärungen in den Vorlesungen des Moduls Internet Technologien I bedingt. Ebenso war das Konzept einer REST-API mir neu. Diese Thematik konnte ich mir aber mithilfe von Youtube-Tutorials verständlich machen.

Ein großes Lob muss dabei an meine Gruppe gehen. Durch die beiden Semester hindurch haben wir gut zusammengearbeitet. Seit Anfang an waren alle aufgeschlossen und bereit an dem Projekt zu arbeiten und zu lernen. Über den Verlauf des Jahres hat sich unsere gemeinsames Verständnis und unsere gemeinsame Arbeitsweise nur gesteigert. Besonders die Projektleitung ist hier hervorzuheben, welche gerade im zweiten Semester sehr auf unsere Vorschläge zu möglichen Optimierungen eingegangen ist. In einem so respektvollen und netten Team zu arbeiten, war eine sehr positive Erfahrung.

Auch der Kundenkontakt war für mich eine neue Erfahrung. Bisher hatten Programmieraufgaben nur einen kleinen Umfang gehabt und waren in ihrer Natur statisch. Nun waren wir hier mit sich ändernden Anforderungen und einem "unerfahrenen" beziehungsweise typischen Kunden konfrontiert. Doch auch hier konnten sich die meisten Probleme mit dem Fortschreiten des Projekts und unserem besseren Verständnis unseres Kunden beiseite legen lassen.



<<<

==== Karl Langer
//Text

<<<


// <<< zum Seitenbruch

